---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: slskd-secret
    template:
      engineVersion: v2
      data:
        SLSKD_SLSK_USERNAME: "{{ .MINIO_ROOT_USER }}"
        SLSKD_SLSK_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: slskd
