---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  namespace: download
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "slskd-config-dst"
  resources:
    requests:
      storage: 2Gi
