apiVersion: v1
kind: Secret
metadata:
    name: slskd-secret
    namespace: download
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:mXmP0NwiAuQ=,iv:w0fVLxEJrTxhQ/2Rvr4VAAxNC3iE/9WVxApf5qm6mZ4=,tag:GqNszZ4jXVgp6ta0lmOH2w==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:YCr86IkluAg=,iv:UMTSPHaEzl1QGMivIeRvuLvTcww0m1XBN8VBfbeFFOc=,tag:XbKwjNqFraKpgRt6BAFpnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x9asfknr3janmqkcm9nlcg5hzm59wtdhs6u9lhweaddagnvg9amq22505d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVnlSUEJEcUYwbEhzSERr
            Y0xPS2c3WHlaTDBZKzB5YWJzQSszRmdBUmhBCmIvSDIzUkJtMmp6REdaTjhtQ29J
            M0QrbkQyOWxXZXhTdDVtUm44WlJwaDgKLS0tIExGTnlzendjcW0zTjdjWkl2bktr
            aHVzbi9Hc1Q2Yyt0bTFDN1RJWEsxcncKTCZ+5b7skpVPW1BQJkm2HvIBpe0XxgW3
            SfBlv0xxIJl4U1sa3iMkCtmIkGIrWh+939Jc980S3sq/56yPU3Jrtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T12:56:48Z"
    mac: ENC[AES256_GCM,data:FXmuLudVK0OTTIif0pHhSLm2xxft9mvIINgJBhKeBbTR7K0EqRBKpi+OysjtJXXGgCFR+7VZlyZIrAh4NwdfbRYMF5O+zzCsjE1KCNJG6Yzbw9r5XqhtqL3i6BgHMhHOX/fvIVKFzlgLU+Q0o9j4M3EB5YI0/fxyc/JxSrSFIkc=,iv:+Msz8g4ctEhprkyUIVclLdYFFcxDxSmnipL1H8mQk9s=,tag:dcHKlRA9gasyMK7pddKcIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
