---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pikvm
  namespace: services
  labels:
    kubernetes.io/service-name: pikvm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  ingressClassName: internal
  rules:
  - host: "llm.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pikvm
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pikvm
  namespace: services
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 443
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pikvm # Must be equal to Service name for automatic mapping
  namespace: services
  labels:
    kubernetes.io/service-name: pikvm
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - 192.168.0.26
