apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oracle-vault
  namespace: security
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.uk-london-1.ertjz47zaabby.abwgiljrurcyvtdeu5len346nlrc7ti6vvtwymltv4qpjpitygqhjbqbgr2q # The vault OCID
      region: uk-london-1 # The vault region
      principalType: UserPrincipal
      auth:
        user: ocid1.user.oc1..aaaaaaaaesiijhpc4ntiyng7rd2do4b7jphcfdngk25mw5e6iavhwz5ckvaq # A user OCID
        tenancy: ocid1.tenancy.oc1..aaaaaaaawmadiqg5ffkzuibopxhzw5eivs5wagays4gpp527orfh2ow4kcmq # A user's tenancy
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
            namespace: security
          fingerprint:
            name: oracle-secret
            key: fingerprint
            namespace: security
