apiVersion: v1
kind: Secret
metadata:
    name: oracle-secret
    namespace: security
    labels:
        type: oracle
type: oracle
stringData:
    privateKey: ENC[AES256_GCM,data:EAHym4f/Zicwq+JYuIXygmiBrJpdH5YK+fxp9HIxpyfO3kgRfxT38RHPvAyBuYtd6vS4dSrXVRLmhnmF9QQ8N86Gc2wQH1Y54c/d+gy1I+xEyUjYm/Prq0duk/5cKyGsVsBVSLfxIIm9/KTmGmUgb8Afv9WImL/rNN4Mm2JMJoddWrLY69qBIlh61U5iv9E4pO97uT/1XImv/Ng8UlGByOC3OqE8foaOvgb1mU4tZZIHKUyucIaBLkyrdUhmFWVlFGupWAe65GmHi4C0SXFpSWh8T3BqXCV6LpWu+4yl1tgYY5QdlM9+8D64maPDohGwO4ZCaMZcCw1SpNSzu8zxYNmq+ulje8pMYDKPX98MlYD7eorwi6dtFt68HDDgc1MHpdKWHv3xskr/rlatT1zR3DNlAiAGqu3SNKK8HKMp5Djkt7vAHgeDb117W1k7iNlddJOTqCEhopXYf0Hgg95eSNLuJlkx4y+6i2Azmomtvw1jehWGUrqRiKgfwtahSa7c5ZqgwQF10r1YXZeEXWtNthVy9I7AXgAVoapAt1eIlFjcql2p7KwPeNimvYc4JcZAuJ4XEF6yo4NnepTTQr/LSG/7wHLUophZoiP7PuVN/z8VJsT1oCHXxk5MhlVOyQD7RdwqIZ1+Lfyv+tCYqVjYROzIX0fWJ/BzlsV+WIP7kt8nvxWFGkWZBhuCwedDVzZH9+SENqvjjxEJ2Srgc1oMIoFemvF7k9m9SHqSq/ulq6jBkgDD3/71267y6rVE+i2G3m7Cp9GwEwVikOt7s7GjJdnKvvMxfYu+rLQCIaZE2WUQwaGECmTT1s1Rr5w8XernlC8+uaYp/bWXIEnVjSV5SPk0VoPq71IqwK/vIHltxUa1MZr5D5pGDYMrZIUZ38TFZV21EYe3MLaMxI9INCZ4legWGSl/3bfbPagYfOoyHSlkR7CNUuLgT+KdFi9ij23jKm91+31+ViqoQ7ImvswPJsXXhJu18gzntNGRnPuoc3hog4nhqIESiI7vBXIOOjbLPmMZ6R63+quuAUgvevMqUHjaMX7B1zqfu4TKZ/tXcn9Fshu0VRZxOYifICuYGh+Q+bpOfvy7FVqH2WSuxswXVB7wFagxfrFHcZ/OIeFzKj//5jqc0UDhb0hHLWR3qk8nYGPwBEUPmsekOGTAZUuU9ZDcitxK0/htY6Oo1197dwou5u0xvmuohOc5aUyL2fjXPEbOHBAiE078SPPjVd0jFkHPAcIN0z1uMjAn/DDzL7dpfl+cVs5HFr0vmrUWPk6rkABIDys8WSzt0UoHs2M81p5SVqBK2v/o+XVRZWzeRNloPHLQo3LcfkETVi5K7ZyUnNQRx+N/sY6J0mtf9jKr02ZTzcdblgfSmGRST+TzlsZIGKCAvfv0qdNqcbitRnqDdXg6rEdOz+U7+Eh6e9o0mgcGNCHPGeMNRhEIZFHg/wBYTx70HBU1RWMVwJaQKFFqGYwqkoPlio5B3ShmC6AGitf7f1lksdE+3TUNgyM+coY1778I6X+obBPZLKH8PFMYdSUSEyg9/g23cGc2/inW25SlhOrmgLucPJpduwS19ucSs1vy8udogEBv+8sepUDR/4S82IDntq14APvEBxNMK6QDUhtvi2w6yQ2mnABYSjyT6bX4rEUdD1hPchG6XVF6v3jkH671/jSyR+RQnJGzQ+L4pL4K+cGAu4f1+F/ItPFPsrhZqLGv3MDWUO2qOAeARFW81c5avoJ7pGPiyeP1FIu5dBl8TgOPVE2MuGc/aE8mDorF7DTqnFhN3FfBWo/BeNmyZgEfAj8A9kEBUoIzfmlzRa6q1/pWklr0LSEZvnEeHUtvybhJSnDDOMEfUigyqqHK9w3o6Xba3dXiOeIRjNAHu8VfxFoEpTg/HwVOmMoIg5Os/5RN1/oCKYOPHei4SNaZ8GemEXJKgd0MhgAChz8OysyiBe63uCANwN9VEcPpsbR+67OpRLwkDPLb9j3h+eXFDDWHq9fDcy5B3xKe3495oauFX0CxCLPUKY8ypQzU/ujoR3Qa39MDcfpKcYIFbSeZGkv2ZiKVXwCsO3vN6tkz47OtUe0qlafODgGnCpn5/Qly1MM2ICuuXonQ+Ydxf3kQDvvh2obtvCW7ByZo42UtUR0TLp78m+uohUlT6zxJkUJ92yI74Aibl5To671bpwnT7m5DA8rHgiKSeqrFJPKWfjfPqaJma2l7uQYQ2zdBzgst5OQ+n700cxabpTK7MHQBGaTTi7xhJlShnNPuH7o3p8pXGxoJ,iv:fs/IiGWZvtCE+qDMGtTbuSUrN4qnKn6b+94S3bc7UXo=,tag:AWA7rAEU38c4RoWpQQ/aTQ==,type:str]
    fingerprint: ENC[AES256_GCM,data:qlAyQxQDxfAB10mIjjb8SASruLv5tTPIflNvjsjv+9D/iyZY5Uq2z+THrOqNI+o=,iv:cvunnh99Rfd9OkFGi+JONDLKWapp0MB+ZGyAvnBgWJI=,tag:YZTc/LYg5J6Aw2SVgB3QFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x9asfknr3janmqkcm9nlcg5hzm59wtdhs6u9lhweaddagnvg9amq22505d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V3FHMmd1K1lScDlNdzR2
            N1BRa1YreitaYnVwN1JWNlZWckVXeFNLRVFrCnAxUUdwYWY0Q1F4N0lPb3Z5dWw4
            Q2lYS2ZXOGFZajdTdmx3MGdhS1hKQjgKLS0tIGhObVpqbXloUDNXaXBMWng3R1FF
            OVZ0SlkwSDVZYWZoRitRVzJNbjl3dTgKRN1ingt8uw0W2ufQAzNz9EHxCw+i3dZD
            nYZC4DlvMHs/2doAKiXRYHvfbRXemg9WaGYw/fmpENYory2mvuCAjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T11:14:50Z"
    mac: ENC[AES256_GCM,data:vsWCzQDw0f5jAl+1Qh+nV/o9ixkxJKJJebyt9BPBBHgf4HnzbFCsvaDtV82mw6muYwdGh/+eRaxl/FatcBCcaOqWN5rBBobVYe30mcQmXKcLX29g256Fl42XAq4tbxVbskjG4wa4BLPDVFcWobuER/9u0W1zM2A3XhpJu6gMuhM=,iv:Ni+XdPlAWhLLoXKFbzcONvyL9tNMbmx1p/3IRa5PC2g=,tag:MDDOcaEmdVGn/hmcz4ylNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
