apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: media
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/bionis/appdata_backup
    server: 10.0.10.18
  persistentVolumeReclaimPolicy: Retain
