---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: minio-secret
    template:
      engineVersion: v2
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: 9TPuKHDGB8T5qMp
  dataFrom:
    - extract:
        key: minio
