---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minio:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-07-13T01-46-15Z@sha256:be3db71ebafc2f4b1ec08330f37417b9c316d088447d88e501be075515214cab
            env:
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}
              MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
              #MINIO_PROMETHEUS_JOB_ID: minio
              #MINIO_PROMETHEUS_URL: https://prometheus.${SECRET_DOMAIN}
              #MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
              MINIO_STORAGE_CLASS_RRS: EC:0
              MINIO_STORAGE_CLASS_STANDARD: EC:0
              MINIO_UPDATE: "off"
            #envFrom:
            #  - secretRef:
            #      name: minio-secret
            args: ["server", "/data", "--console-address", ":9001"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: &s3port 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              privileged: true
              runAsUser: 99
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 3Gi
    service:
      minio:
        controller: minio
        ports:
          http:
            port: 9001
          s3:
            port: *s3port
    serviceMonitor:
      minio:
        serviceName: minio
        enabled: true
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      minio:
        enabled: true
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "Host $host";
            more_set_headers "X-Forwarded-For $remote_addr"
        hosts:
          - host: &host "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: minio
                  port: http
        tls:
          - hosts:
              - *host
            secretName: minio.tls

      s3:
        enabled: true
        className: external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &s3Host s3.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: minio
                  port: s3
        tls:
          - hosts:
              - *s3Host
            secretName: s3.tls
    persistence:
      config:
        type: nfs
        server: 10.0.10.18
        path: /mnt/mechonis/backup/minio
        globalMounts:
          - path: /data
