apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: security
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:1vftDIo=,iv:NxdEdeidQ9CayTjv2QHgQVGsKHiHQu66HkhiBVpYhYw=,tag:mjM0oOI+cYTCQvL/WGFvHw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:rQNrSvB88enp443vExwC,iv:KzskNxQ2Gjb/3nve4HgenLJb0H5dlB0IQFWueFXLJik=,tag:8XeF7jM4s+H5oCMata4Dhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x9asfknr3janmqkcm9nlcg5hzm59wtdhs6u9lhweaddagnvg9amq22505d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVFp4RFFjYnFyNGc2RUY4
            eWpvV2pQbzFiNi9kRzFDQ2kvYi9GTzM1alVJCjNRamF0OStkdG4xdXNNWjRHYWg1
            NG5xN1hHbDAra0JGTmlsM0JTTUE4ZzgKLS0tIDA2Rkl4bjZjM3RSOTd4QVg1dGc1
            Q3ZlV1hzbkRFSXZob3UwY0NGTGpnbVUKj9gYDIVMxPQQ3pra7A9EGd4UH40A2Rai
            bZEdqYBWa8IszPElEm2qBM0vQjVWkelNn/jwBSYEzN6cRMwKqpVYlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-16T11:33:02Z"
    mac: ENC[AES256_GCM,data:2wXpX5B3k/BXLw4sgi7bBB2RkRwLXpLb2EyuVVuVa261zzgKZMGhcc7XWFvDluVOdyWiNydZO2ri5GVHQB6lA3qIBR31SvvhHI91yqX8wI3d10zykETXb+ZJWmw/pxtx+xjmui5nRxjwY2KXVFAyoKqbqYAiVh+26qH1hLCITlo=,iv:4IdZMOpt9veXUjK5JcM7f16qE+dfCTYDQRECV0h8RlU=,tag:ONBwF3qJy1g1ds3uIrGr3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
