---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: security
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "vaultwarden-config-dst"
  resources:
    requests:
      storage: 100Mi
