piVersion: v1
kind: Secret
metadata:
    name: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:NNgTdIPVv7hjBUR7LILz5t4pwdhNzwWLHr9edb6eufhz72cPrfMcS3jE/MH5jJmL,iv:GfJU7VnXiIIbgdbtw6M2F6BZCS9opyPaXf/gBoxz5kE=,tag:122QZglX+AqX783NfFeM9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x9asfknr3janmqkcm9nlcg5hzm59wtdhs6u9lhweaddagnvg9amq22505d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT1JqVld6SWNXbjR6ZThK
            RWI4VFhXZHBTNXlxeEcyL1V4N1I5STlEMkRnCnNxeVNuSUM1VjVpVnkrMlFDT2lH
            QnlUM1JsTUhOU1NoUC9RSjU4YW1QS1UKLS0tIHdZVzhTL3VoaEROeGh6eUNBVFgz
            MWVEb2c1cm1FWVVCU0VPT1RmYmdTc0UKGkaPvYutcYh9YZ83NCvsvMJquJnWet8H
            N9SuobLuGkwXiNzHAl4Sp3iL+7uEBpuup7KpMtU2ulBYHohxyykL6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-03T20:27:55Z"
    mac: ENC[AES256_GCM,data:sLjXBEP8yVYob2rAfsynREfpFK8sci62NVBD6N7d42wbeY1gu5NwxGHeaOOkMgT7oEKqzf5iYQz9unBOFO5i7k/R7gIaexwfhvW9Ld/VRmcQguJUs03yfOl8BcEs/hlWFinKAuY4rbqMU3yV8WWI6EKEN6ti2X/g7N2GiRdvsX0=,iv:ry3GvdPivXMNIgVj3dnnkENG318bx3fDy4a/g0Z4pxA=,tag:mTb8RVTT8GCNXvZn0c8FuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
