---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: "8pUZvurLfZfCiPVcfwJ7bNwoy8Pup5Hs"
default_redirection_url: https://auth.wabbit.life/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers.read: 4096
  buffers.write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug
  format: json
  file_path: "/var/log/crowdsec/authelia.log"
  keep_stdout: true

#webauthn: #FIDO2 Authentication
#  disable: false
#  display_name: Authelia
#  attestation_conveyance_preference: direct
#  user_verification: required
#  timeout: 60s

totp:
  issuer: wabbit.life
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8


access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain:
        - "auth.wabbit.life"
      policy: bypass
    ## bypass api / triggers
    - domain: "*.wabbit.life"
      resources:
        - "^/api([/?].*)?$"
        - "^/identity.*$"
        - "^/triggers.*$"
        - "^/meshagents.*$"
        - "^/meshsettings.*$"
        - "^/agent.*$"
        - "^/control.*$"
        - "^/meshrelay.*$"
        - "^/wl.*$"
      policy: bypass
    ## block admin
    - domain: "bitwarden.wabbit.life"
      resources:
        - "^*/admin.*$"
      policy: one_factor
    ## bypass rule
    - domain:
        - "bitwarden.wabbit.life"
      policy: bypass
    ## two factor login - admin
    - domain:
        - "proxy.wabbit.life"
       # - "portainer.wabbit.life"
      subject:
        - "group:admins"
      policy: two_factor
    ## one factor login - moderators
    - domain:
        - "sonarr.wabbit.life"
        - "radarr.wabbit.life"
        - "nzbd.wabbit.life"
        - "prowlarr.wabbit.life"
        - "wabbit.life"
      subject:
        - "group:admins"
     # policy: one_factor
    ## one factor login - requesters
   # - domain:
   #     - "petio.domain.com"
   #     - "overseerr.domain.com"
     # subject:
     #   - "group:requesters"
     #   - "group:admins"
      policy: one_factor
    ## one factor login - catch all
    - domain: "*.wabbit.life"
      subject:
        - "group:admins"
      policy: one_factor

session:
  name: authelia_session
  domain: wabbit.life
  same_site: lax
  secret: "pdMiO74lOZySbf8uTWpe6cocnLgH5NFr"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M
  redis:
    host: redis
    port: 6379
    password: "G6NicaWxaxc2XZ"
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: "aZJQsL3FHjAz7R9CzMyXl0AR9lUCwdY7"
  mysql:
    host: mariadb
    port: 3306
    database: authelia
    username: authelia
    password: "a8nbbMptixJFLr"

notifier:
  disable_startup_check: false
  smtp:
    username: wabbitlife518@gmail.com
    password: "wgfp bpmj fjaf fthj"
    host: smtp.gmail.com
    port: 587
    sender: authelia@wabbit.life
    subject: "[Authelia] {title}"
    startup_check_address: phycoforce@gmail.com
    disable_require_tls: false
    disable_html_emails: false

identity_providers:
  oidc:
    hmac_secret: MhKEwzpNoJjF8dqcQooUp2UJKiRjgRxTyDgboFrgaVvismJWsfFX8a6KIcUJU0zr
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKgIBAAKCAgEA1ug5so8SPj+ruKnxhSdz+JzizCvc899VrTrGOyBJV5wRa4fX
      Q9aQLHLe3h1UnsUSYyRirUuRZ4Byq8cdG76LDl+akFw3ilSySQbvyDEOLztPo0Yh
      leHiB2xLghjUUur8F9QBz8JkffkUaJSBxnjxsmca3kL4tJchghim6Qc12omoo4rh
      BTtwDwA8Loey/yd8c69f26lLJxMad7x+lcmoekFkApKoi8g+M+L5EfM3jJI3b1cB
      N64uXP9sjEtQP6pFvheBsOcBYBOcOxxhNluYsu8IXoAISR95oT0UD7wAK2rJ7SAX
      NgxGTqUFQxKcJk3JAQAG4xCoiDlB/3or2IYIM64+LZ2+J4tSkj1nkZ5Ix4HLp0dw
      AiFjd30oNXcN9XkCBirvF3kNQ2fQtJs0jKkQ3hV4j0yyD63SPlfB4dF+7e6CwhWu
      koTBx9CT4Usw221AjYQ+Kz24p50uvoNwpYp/Wyq3OT9O23RslrhO8Rp3ncVzkzyU
      ZvCg/NqYmVonPrxo8JoVQjwMw0XgQSqOSyfEnScW/wuwXy1LnJqL8Uxy3+2x9Z5F
      XhAnuSKV/3g4AR0Ok8usuSTxxHg6yeLFvr2G/dD4HunHnbYrNu/gE0g+lvuP2ST8
      ghkaXnnzuqB1rYzGNJ9Ug3LHMoKEUJoa3nswPZC/hhnQOxL3PkmHifC8YQ0CAwEA
      AQKCAgEA0EX7NNuHWKCoMa0xjlQwBm81NZ4E4qw9AkeFueOOcMOl9kqOCwa0bv9c
      knJmggCH02F96GjmICLR/zxXL344kdOBngphIUT4C+IXHDK+hnO6uIfNIM7rGTqQ
      6yJZE4r8ibNDli/U6GkuqDPUmZ64zqcx2Nma4pndNZHioNAGFyd2Mhjz/vgdn8wg
      hw+oH7QK3qrGAcJOPS48ZnJdU5k+GE2rOPsdMWr9LZf4vraxzSAfbV4qpeW+tQ4u
      CsEqoqjIMnPhkqouIQigToEwjVez4yXZPIxke0lvvR3OhXkzyOATliWVmSHIOYug
      T+KHRm/4L2nxQrnwOyUSmx+xwoQTCQw4I20nxYWGayvUloNsxv2MA1TqiRwCzDVS
      U3xLSa/Ohed6TbS7bMTHjCVL62cArrejic6jhS7l3bpsf77obgPBwgEjF2v04jYt
      /U2Bq8oe0tfsGn+C+BnVf8RpJbMlRlxrL4c0LouIMsQ+ScOk/KPkrumLkne4tjwo
      cnKLp97xXlsbhdHNopDkF6eXCBUaIg/dc7+qFbPkhVMHhBKYXQwM8xE+GklS8yV8
      8KxFRpdmPpE79Zv0DSyMajgOTC2v+IKvQaiztf8z9RAH5TKkbeybjvG5WoqeQW5R
      hE5P/B0z69autT7i1lcWJBoRTcejKvvIHWa5Fbg32T+9KJ9g2IECggEBAPDBzcPe
      aVtR1Ne8B/MA3eViabANgMZjzXdr6Znw4sBDhbVUVQrtbbphRNkayro2BZ5y8QEu
      GY29dn+TQrfBqFEXyaQbdnJ0bIAdS0hXrSATN+tPKjWxAdJup0I2x9guLRzuU1EW
      5SgiWEtJQSySkPzdhOMuq0dDuVA8fqDu7wjNZ/trNEIAthFK8hif2VXfXZlE9epB
      F+kF4rWJOkBO/a7EH7PlXocAiTbtaAyE2R9iPM1c4I7/y3NN85oZQu0ZYo83L5FJ
      Zwsd/TJ5kInC/Jt4DSbt7xyVv6IYv1toweE0G3US9nyHxIdpQ61BoJ7j21ImIXR+
      6pLot8roqSvJeDECggEBAOSDcg5fMjD0UI/Kd561UVNEhKnQMbNNNk+tzIzq4EMZ
      Ehnymxhnp3AB7/XadURkXvsrHQAdE60RTcGV6s5JIVrVSGITmmki59loBX3f7EG8
      WkD3P7uo+nCH5dDTKFmsDEMxL7J4VPhWaDKCeYxwjmFREJ8d7HeOr/PGBrxa+Q6n
      azHGHKiv+6NNJpaA3q2SH9dXN3ASj5Nsrlxcj5ZbIwQZKw6rgF1FWbEmYMbjdJ47
      rSlt4PQgMPIONRcFzQwObUoGgHjODpu6O/kMsA3Soz8f6pJNLS5yLRz+HBqPAsCy
      8YzA+4wa/Owy04dLukYGg8RtU2ZCxz6mWCkQt47om50CggEBAJupYqXCdrIhfZEi
      tK0MIWv/LkAy6tDalG0jK31pvuH6hkfQR8/x5SE9ZKtOZEbzSLzCqkpOCR2YozYm
      +1sd7frIe4oMa4/i8IgA6LzUW05CvsP4gl0Gnhv1iVUJYDrI2Eg9W0cxm2ZQlm/O
      5EGyXeXwP8w3T2ybQAS9qE3bTleNny5yiO4n0Y/qug7rwzR/X+AKM0mLXq8+K++d
      0zjjGahWi/zfTzfQQ+dspfp6JnvhI1jQNSyf/GYHv3oh3SC5af0Y/Dtejy4j7KIm
      8SnxFSxb+XzzF8eOlsFyaL7sQ3adHyeZ5B5uFcZLbANoTDaPMi2yE61jpbzolHSv
      6zkxYPECggEAb59ZvnV34fvlwmdnSSpOwHruxriBHpGv3voJuigdRglgEzaz1hcD
      7i20FocQ00ioMM6diumpK9gRAGgH255TYbhfdDEZMxQu5r7uN8+C65VjDOr5weRH
      +WIYu4n54tus3cGQCADJmMk0er/LOfPdSOI9WUxXrwsPHef0cFuL30GeliCs7SWR
      qPJN0CTBIU4IqbrbxK38XkovXcSFCzAXia/1nWPe/zCaIHObwGtpEsYZzuvyf62d
      2w9flZBq2eHONuO4K8qTzjQJiZ1N/mKPBY3EmpSCZna1XL0v4zVKZfDDFztJZOXl
      +EbXlvZB1mTmRrQUkhY6l3rQA7c7wt4S7QKCAQEAzwLNey/7mff0BUmVXJ01C0sH
      2c1O40TkcUQIBq/m5X4ZJsG0TyCAS4v/mYjtRSkaNglFoKeLmjqSymaCxfPoukOS
      vnmUQHPwIJChgMmrcwAjgTlap6/9E4xbqMEtAXge9CM9oRFJrpqDKbDhyjYEXzGd
      3pIGz5NaUKE5hsg/pC50Kk22iFKdiftlpubZi0Ul7+29S6NTV+aKna7FstADuOVm
      mE7Al7an5y5A2MeVZtD+pmkaMe+7bBjJULfRGhAQVYWEm6W4p4m5UYDRT/e5qyaQ
      WKiRkyqSqENVc6AAHsTVogt6Xt//V3zZrHCi4fCXlgVfoFsH15kfXuedMzWrng==
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - https://auth.wabbit.life
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'synapse'
        client_name: 'Synapse'
        client_secret: '$argon2id$v=19$m=65536,t=3,p=4$8xpeLG7vf1wJ4ghtNy7s9w$I4cEev49OwBtUMvkcM0Ah5mSEMecCD7OD/SHc7KfFjo'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://m.wabbit.life/_synapse/client/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
---
