---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "prowlarr-config-dst"
  resources:
    requests:
      storage: 1Gi
