---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "radarr-config-dst"
  resources:
    requests:
      storage: 5Gi
