---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-synapse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: matrix-synapse-secret
    template:
      engineVersion: v2
      data:
        PASSWORD: "{{ .SYNAPSE_DB_PASSWORD}}"
  dataFrom:
    - extract:
        key: matrix-synapse
