apiVersion: v1
kind: Secret
metadata:
    name: matrix-synapse-signingkey
    namespace: communication
stringData:
    signing.key: ENC[AES256_GCM,data:jzlSikEk+QbVJqtYOFe2A++Ygo4Tab32s1Xn63+jGcEf0CVJ+ighvv2tb8eJ+GAfLUIXb3djv28b/A==,iv:7qBvLOPHDDUlM4YG5tkrqpdgepnPEyAbRKYGipe5MkI=,tag:m2959UlHm5F9Kj5l2NhQ8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x9asfknr3janmqkcm9nlcg5hzm59wtdhs6u9lhweaddagnvg9amq22505d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN1o2UzdDb1pTR0tQcjB0
            ZThzWFFIUDJmN2tsR1RKM25yeTBXRjBJeEVrCnpXZFFBL2FYVExhcktCdC92ekpQ
            d1dEZTBYa3R0eUdURFdiczN6V2IvWVkKLS0tIENVWGo0eS8wRjBSZHo0NVVkMlAz
            Y3VMSHpZVm5mR3Q4UHZtbGNmVjFXZTAKJICITSBBgTm0UteoEw8Qn6YginbQAWDg
            /NBU07hvnHF6wtuaY0arZ/EnkxEnL202DuMipmQbA2t+pASjZbUYPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T15:15:16Z"
    mac: ENC[AES256_GCM,data:MUR/PCyUsHBEFotJgj4Nn56+uOrpQpwGy3Adx0ET3kLBY8Q2FhMWwJcO3QZKN1gsAtS2r1AopQ2I2pwoQZX/VxlOFm6pntE2qisXv3jlb1HIEbSVA5PWmFP7yhHfEBW8+FKhF1/xp63IpqQ8yzpTi/9NlbkzMe9Jr093ei5FcZY=,iv:zgKjIpysvDEthXET5fQJG1+LRlmoJGlwJfbT2arkusk=,tag:a7a4ZbGOncbUdFY3QyEjXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
