apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: communication
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-snapshot
