---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: communication
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "synapse-data-dst"
  resources:
    requests:
      storage: 20Gi
