---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: teslamate-secret
    template:
      engineVersion: v2
      data:
        # App
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        DATABASE_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DATABASE_NAME: &dbName teslamate
        DATABASE_USER: &dbUser "{{ .POSTGRES_USER }}"
        DATABASE_PASS: &dbPass "{{ .POSTGRES_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER_FLAGS: "-s"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: teslamate
    - extract:
        key: cloudnative-pg
